version: '3'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: www_app
    volumes:
      - ./:/app
    ports:
      - "4200:4200"
    restart: unless-stopped
